[app_servers]
# Replace with your EC2 public IP
ec2-server ansible_host=<EC2-PUBLIC-IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem

[app_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
